services:
  - type: web
    name: backend
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
  - type: static_site
    name: frontend
    buildCommand: "npm install --prefix frontend && npm run build --prefix frontend"
    staticPublishPath: "frontend/build"
